name: "Configure git user"
description: >
  Configure the git user (name and email) using a personal access token
inputs:
  token:
    description: >
      Personal access token (PAT) used to query for the authenticated user.
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"