name: Publish Action

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency: publish

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Node.js dependencies
        run: npm ci --omit optional

      - name: Run @vercel/ncc
        run: npm run dist

      - name: Update action.yml
        run: sed -Ei '/pre:.+/d ; s/index.js/dist\/index.js/' action.yml

      - name: Create tags and publish
        uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
